# Generated by Django 4.2.27 on 2026-01-29 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be 8 digits and start with 6, 8, or 9.', regex='^[689]\\d{7}$')])),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Postal code must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'slot'],
            },
        ),
    ]
