# Generated by Django 4.2.27 on 2026-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='worker_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
